# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app_launcher.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('web', 'web'),
    ],
    hiddenimports=[
        'config',
        'models',
        'pack_argument',
        'novel_packer',
        'scheduler',
        'logger',
        'version',
        'plugins',
        'plugins.base',
        'plugins.repository',
        'plugins.crypto_loader',
        'epub',
        'epub.packer',
        'epub.constants',
        'epub.cover_detector',
        'utils',
        'utils.http_util',
        'utils.html_util',
        'utils.url_util',
        'utils.volume_util',
        'utils.sequence',
        'flask',
        'flask.app',
        'web.server',
        'playwright',
        'playwright.async_api',
        'playwright.sync_api',
        'webview',
        'webview.platforms.edgechromium',
        'bs4',
        'lxml',
        'PIL',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Cipher.AES',
        'Crypto.Cipher._mode_cbc',
        'Crypto.Util.Padding',
        'Crypto.Protocol.KDF',
        'ebooklib',
        'httpx',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.padding',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'cryptography.hazmat.primitives.ciphers.modes',
        'cryptography.hazmat.primitives.ciphers.aead',
        'cryptography.hazmat.primitives.asymmetric.padding',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.backends',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ScrollPack',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='web\\icon.ico',
)
